### PR TITLE
Fix update property

### PR DESCRIPTION
**Pull request by 1Nixx**

### CODE REVIEW

**Comment by dimabezzubenkov** [comment]
@1Nixx The idea behind the repository package is that it never calls Save(). Save() triggers EF context validation and is pretty small by itself. By using the repository we can make multiple updates/deletes/inserts on the context instance and then call Save() only once. It will trigger the context validation once. And it will send one SQL statement to the database (it still will be multiple queries though just because of the nature of SQL).

**Comment by 1Nixx** [comment]
@dimabezzubenkov Yes, I know that in the repository we don't call save. But I changed in services. If we call UpdateProperty in services now it doesnt save changes, to save changes we need to inject repository because there is no saving in the service.

**Comment by 1Nixx** [comment]
If user would like to change different properties, he should use repository. Becouse in services one operation = one SaveChange. But in repository you can call many times UpdateProperty and call SaveChanges once

**Comment by dimabezzubenkov** [comment]
Yeah, I didn't notice that the second file was in the services repository.

**Review by dimabezzubenkov — APPROVED** [review]

**Pull request merged**
